version: '3'
services:
  mongo:
    image: mongo:3.4.23
    container_name: microcks-mongo
    volumes:
      - "./data/mongodb/:/data/db"
    ports:
      - "27017:27017"

  postman:
    image: microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime
    ports:
      - "3000:3000"

  microcks:
    depends_on:
      - mongo
      - postman
      - keycloak-server
    image: microcks/microcks:latest
    container_name: microcks
    volumes:
      - ./config:/deployments/config
    ports:
      - "8900:8080"
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: ${MR_SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${MR_SPRING_DATA_MONGODB_URI}
      SPRING_DATA_MONGODB_DATABASE: ${MR_SPRING_DATA_MONGODB_DATABASE}
      POSTMAN_RUNNER_URL: ${MR_POSTMAN_RUNNER_URL}
      TEST_CALLBACK_URL: ${MR_TEST_CALLBACK_URL}
      KEYCLOAK_URL: ${MR_KEYCLOAK_URL}
