version: '2'

services:
  mongo:
    image: mongo:3.4.23
    container_name: microcks-db
    volumes:
      - "~/tmp/microcks-data:/data/db"

  keycloak:
    image: quay.io/microcks/microcks-keycloak:20.0.2
    container_name: keycloak
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME_ADMIN_URL: "http://localhost:18080"
      KC_HOSTNAME_URL: "http://localhost:18080"
      NO_PROXY: $NO_PROXY,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak,async-minion,postman
      no_proxy: $no_proxy,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak,async-minion,postman
    volumes:
      - "./keycloak-realm:/opt/keycloak/data/import"
    command:
      - start-dev
      - --import-realm

  postman:
    image: quay.io/microcks/microcks-postman-runtime:0.3.0
    ports:
      - "3000:3000"
    container_name: postman
    platform: linux/amd64
    environment:
      NO_PROXY: $NO_PROXY,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak,async-minion,postman
      no_proxy: $no_proxy,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak,async-minion,postman
