version: '3'

services:

  apicurio-studio-db:
    image: 'postgres:15.2'
    environment:
      POSTGRES_DB: ${AS_DATABASE}
      POSTGRES_USER: ${AS_DB_USER}
      POSTGRES_PASSWORD: ${AS_DB_PASSWORD}
    volumes:
      - './data/postgre/:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  apicurio-studio-ws:
    image: 'apicurio/apicurio-studio-ws:${APICURIO_WS_VERSION}'
    ports:
      - "8092:8092"
    depends_on:
      - apicurio-studio-db
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'
      QUARKUS_PROFILE: ${QUARKUS_PROFILE}
      QUARKUS_HTTP_PORT: 8092
      APICURIO_HUB_STORAGE_JDBC_TYPE: ${APICURIO_DB_TYPE}
      APICURIO_DB_DRIVER_NAME: ${APICURIO_DB_DRIVER_NAME}
      APICURIO_DB_CONNECTION_URL: ${APICURIO_DB_CONNECTION_URL}
      APICURIO_DB_USER_NAME: ${APICURIO_DB_USER_NAME}
      APICURIO_DB_PASSWORD: ${APICURIO_DB_PASSWORD}
      APICURIO_DB_INITIALIZE: ${WS_APICURIO_DB_INITIALIZE}
      APICURIO_SHARE_FOR_EVERYONE: ${APICURIO_SHARE_FOR_EVERYONE}


  apicurio-studio-api:
    image: 'apicurio/apicurio-studio-api:${APICURIO_API_VERSION}'
    ports:
      - "8091:8091"
    restart: on-failure
    depends_on:
      - apicurio-studio-db
      - apicurio-studio-ws
      - keycloak-server
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'
      QUARKUS_PROFILE: ${QUARKUS_PROFILE}
      QUARKUS_HTTP_PORT: 8091
      APICURIO_KC_AUTH_URL: ${APICURIO_KC_AUTH_URL}
      APICURIO_KC_REALM: ${APICURIO_KC_REALM}
      APICURIO_KC_CLIENT_ID: ${API_APICURIO_KC_CLIENT_ID}
      APICURIO_HUB_STORAGE_JDBC_TYPE: ${APICURIO_DB_TYPE}
      APICURIO_DB_DRIVER_NAME: ${APICURIO_DB_DRIVER_NAME}
      APICURIO_DB_CONNECTION_URL: ${APICURIO_DB_CONNECTION_URL}
      APICURIO_DB_USER_NAME: ${APICURIO_DB_USER_NAME}
      APICURIO_DB_PASSWORD: ${APICURIO_DB_PASSWORD}
      APICURIO_DB_INITIALIZE: ${API_APICURIO_DB_INITIALIZE}
      APICURIO_MICROCKS_API_URL: ${APICURIO_MICROCKS_API_URL}
      APICURIO_MICROCKS_CLIENT_ID: ${APICURIO_MICROCKS_CLIENT_ID}
      APICURIO_MICROCKS_CLIENT_SECRET: ${APICURIO_MICROCKS_CLIENT_SECRET}
      APICURIO_GITHUB_API_URL: ${APICURIO_GITHUB_API_URL}
      APICURIO_GITLAB_API_URL: ${APICURIO_GITLAB_API_URL}
      APICURIO_BITBUCKET_API_URL: ${APICURIO_BITBUCKET_API_URL}
      APICURIO_SHARE_FOR_EVERYONE: ${APICURIO_SHARE_FOR_EVERYONE}


  apicurio-studio-ui:
    image: 'apicurio/apicurio-studio-ui:${APICURIO_UI_VERSION}'
    ports:
      - "8093:8093"
    restart: on-failure
    depends_on:
      - apicurio-studio-api
      - apicurio-studio-ws
      - keycloak-server
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'
      QUARKUS_HTTP_PORT: 8093
      QUARKUS_PROFILE: ${QUARKUS_PROFILE}
      APICURIO_KC_CLIENT_ID: ${APICURIO_UI_KC_CLIENT_ID}
      APICURIO_KC_AUTH_URL: ${APICURIO_KC_AUTH_URL}
      APICURIO_KC_REALM: ${APICURIO_KC_REALM}
      APICURIO_UI_HUB_API_URL: ${APICURIO_UI_HUB_API_URL}
      APICURIO_UI_EDITING_URL: ${APICURIO_UI_EDITING_URL}
      APICURIO_UI_FEATURE_MICROCKS: ${APICURIO_UI_FEATURE_MICROCKS}
      APICURIO_MICROCKS_API_URL: ${APICURIO_MICROCKS_API_URL}
      APICURIO_MICROCKS_CLIENT_ID: ${APICURIO_MICROCKS_CLIENT_ID}
      APICURIO_MICROCKS_CLIENT_SECRET: ${APICURIO_MICROCKS_CLIENT_SECRET}
      APICURIO_UI_FEATURE_SHARE_WITH_EVERYONE: ${APICURIO_UI_FEATURE_SHARE_WITH_EVERYONE}
      APICURIO_UI_LOGOUT_REDIRECT_URI: /
      APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP: ${APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP}
      APICURIO_OIDC_REDIRECT_HTTPS: "false"
      QUARKUS_HTTP_CORS_ORIGINS: "*"

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_IMPORT: /microcks-keycloak-config/apicurio-realm.json,/microcks-keycloak-config/microcks-realm.json
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./config/keycloak/apicurio-realm.json:/opt/keycloak/data/import/apicurio-realm.json
      - ./config/keycloak/microcks-realm.json:/opt/keycloak/data/import/microcks-realm.json

