version: '3'

services:

  apicurio-studio-db:
    image: 'postgres:15.2'
    environment:
      POSTGRES_DB: apicuriodb
      POSTGRES_USER: apicuriodb
      POSTGRES_PASSWORD: apicuriodb
    volumes:
      - './data/postgre/:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

  apicurio-studio-ws:
    image: apicurio/apicurio-studio-ws:0.2.61.Final
    ports:
      - "8092:8092"
    depends_on:
      - apicurio-studio-db
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'
      QUARKUS_PROFILE: prod
      QUARKUS_HTTP_PORT: 8092
      APICURIO_HUB_STORAGE_JDBC_TYPE: postgresql9
      APICURIO_DB_DRIVER_NAME: postgresql
      APICURIO_DB_CONNECTION_URL: jdbc:postgresql://apicurio-studio-db:5432/apicuriodb
      APICURIO_DB_USER_NAME: apicuriodb
      APICURIO_DB_PASSWORD: apicuriodb
      APICURIO_DB_INITIALIZE: false
      APICURIO_SHARE_FOR_EVERYONE: false
      NO_PROXY: $NO_PROXY,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak
      no_proxy: $no_proxy,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak


  apicurio-studio-api:
    image: apicurio/apicurio-studio-api:0.2.61.Final
    ports:
      - "8091:8091"
    restart: on-failure
    depends_on:
      - apicurio-studio-db
      - apicurio-studio-ws
      - keycloak-server
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'
      QUARKUS_PROFILE: prod
      QUARKUS_HTTP_PORT: 8091
      APICURIO_KC_AUTH_URL: http://keycloak:8080
      APICURIO_KC_REALM: apicurio
      APICURIO_KC_CLIENT_ID: apicurio-api
      APICURIO_HUB_STORAGE_JDBC_TYPE: postgresql9
      APICURIO_DB_DRIVER_NAME: postgresql
      APICURIO_DB_CONNECTION_URL: jdbc:postgresql://apicurio-studio-db:5432/apicuriodb
      APICURIO_DB_USER_NAME: apicuriodb
      APICURIO_DB_PASSWORD: apicuriodb
      APICURIO_DB_INITIALIZE: false
      APICURIO_MICROCKS_API_URL: http://microcks:9090/api
      APICURIO_MICROCKS_CLIENT_ID: microcks-serviceaccount
      APICURIO_MICROCKS_CLIENT_SECRET: ab54d329-e435-41ae-a900-ec6b3fe15c54
      APICURIO_SHARE_FOR_EVERYONE: false
      NO_PROXY: $NO_PROXY,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak
      no_proxy: $no_proxy,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak



  apicurio-studio-ui:
    image: apicurio/apicurio-studio-ui:0.2.61.Final
    ports:
      - "8093:8093"
    restart: on-failure
    depends_on:
      - apicurio-studio-api
      - apicurio-studio-ws
      - keycloak-server
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'
      QUARKUS_HTTP_PORT: 8093
      QUARKUS_PROFILE: prod
      APICURIO_KC_CLIENT_ID: apicurio-studio
      APICURIO_KC_AUTH_URL: http://keycloak:8080
      APICURIO_KC_REALM: apicurio
      APICURIO_UI_HUB_API_URL: http://apicurio-studio-api:8091
      APICURIO_UI_EDITING_URL: ws://apicurio-studio-ws:8092
      APICURIO_UI_FEATURE_MICROCKS: true
      APICURIO_MICROCKS_API_URL: http://microcks:9090/api
      APICURIO_MICROCKS_CLIENT_ID: microcks-serviceaccount
      APICURIO_MICROCKS_CLIENT_SECRET: ab54d329-e435-41ae-a900-ec6b3fe15c54
      APICURIO_UI_FEATURE_SHARE_WITH_EVERYONE: false
      APICURIO_UI_LOGOUT_REDIRECT_URI: /
      APICURIO_UI_VALIDATION_CHANNELNAME_REGEXP: '*'
      APICURIO_OIDC_REDIRECT_HTTPS: "false"
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      NO_PROXY: $NO_PROXY,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak
      no_proxy: $no_proxy,microcks,apicurio-studio-ws,apicurio-studio-api,apicurio-studio-ui,postman,keycloak